import { observable } from 'mobx';

class Lang {
  @observable lang = {
    completionTime: '完成时间',
    creationTime: '创建时间',
    Name: '名称',
    name: '名称',
    size: '大小',
    success: '操作成功',
    failed: '操作失败',
    warning: '警告',
    SPEED: '速度',
    error: '错误',
    taskManagement: '任务管理',
    uploadDirs: '上传文件夹',
    OK: '确定',
    Start: '开始',
    StartSelectedTasks: '开始上传选中的任务',
    reupload: '重新上传',
    ReUploadSelectedTasks: '重新上传选中的任务',
    Pause: '暂停',
    PauseSelectedTasks: '暂停选中的任务',
    delete: '删除',
    DeleteSelectedTasks: '删除选中的上传任务',
    uninitial: '等待',
    pause: '暂停',
    error: '错误',
    break: '完成',
    Failed: '失败',
    uploading: '上传中',
    pending: '等待',
    tips: '提示',
    History: '历史记录',
    noFileSelected: '未选中任何文件！',
    fileUploadDoneTips: '文件上传完成，是否刷新界面？',
    noFilCanBeUploaded: '该目录内无任何文件可以被上传！',
    uploadingFileReuploadTips: '当前文件夹中重复上传的文件已经被过滤：',
    upload_startAllTasks: '开始选中的上传任务',
    upload_startAllTasksTip: '确定开始选中的上传任务吗？（仅对暂停的任务有效）',
    uploadError: '上传文件错误！',
    upload_pauseAllTasks: '暂停选中的上传任务',
    upload_pauseAllTasksTip: '确定暂停选中的上传任务吗？',
    upload_removeOneTask: '删除上传任务',
    upload_removeOneTaskTip: '确定删除这个上传任务吗？',
    upload_removeOneTaskHistory: '删除上传任务',
    upload_removeOneTaskHistoryTip: '确定删除这个上传任务吗？',
    upload_removeAllTasks: '删除选中的所有任务',
    upload_removeAllTasksTip: '确定删除选中的所有任务吗？',
    upload_removeAllTasksHistory: '删除选中的所有任务',
    upload_removeAllTasksHistoryTip: '确定删除选中的所有任务吗？',
    upload_retryAllTasks: '续传选中的失败任务',
    upload_retryAllTasksTip: '确定续传选中的失败任务吗？（仅对上传失败的任务有效）',
    upload_restartAllTasks: '重传选中的失败任务',
    upload_restartAllTasksTip: '确定重新上传选中的失败任务吗？（仅对上传失败的任务有效）',
    upload_restartAllTasksHistory: '重传选中的失败任务',
    upload_restartAllTasksHistoryTip: '确定恢复上传选中的失败任务吗？（仅对上传失败的任务有效）',
    continueTransport: '续传',
    uploadFiles: '上传文件',
    upload: '上传',
    uploadFiles: '上传文件',
    uploadDirs: '上传文件夹',
    uploading: '上传中',
    alreadyDone: '完成',
    allTasks: '当前任务',
    all: '所有',
  }
}

export default Lang;